config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'invoices#index'
  resources :invoices do
    post 'send_invoice_mail', to: 'send_invoice_mail', as: :send_invoice_mail
  end
  resources :clients
  get 'view_invoice/:uuid' => 'invoices#view_invoice', as: :view_invoice
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :invoices
  belongs_to :user
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :client
  has_many :items, dependent: :destroy
  accepts_nested_attributes_for :items, allow_destroy: true, update_only: true
  def invoice_number
    'INV%05d' % id
  end
  enum status: {
    draft: 0,
    published: 1,
    paid: 2
  }
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :invoice
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :clients
  has_many :invoices
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    @client.user_id = current_user.id

    if @client.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def client_params
    params.require(:client).permit(:name, :email, :user_id)
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  skip_before_action :authenticate_user!, only: :view_invoice
  def index
    @invoices = current_user.invoices
  end

  def new
    @invoice = Invoice.new
    @invoice.items.build
  end

  def create
    @invoice = current_user.invoices.new(invoice_params)
    @invoice.uuid = SecureRandom.uuid
    @invoice.invoices_total = invoice_params[:items_attributes].values.map do |item|
      item['price'].to_f * item['quantity'].to_f
    end.sum

    if @invoice.save
      redirect_to invoices_path
    else
      render 'new'
    end
  end

  def show
    @invoice = Invoice.find(params[:id])
    @client = @invoice
  end

  def edit
    @invoice = current_user.invoices.find(params[:id])
  end

  def update
    @invoice = current_user.invoices.find(params[:id])
    @invoice.invoices_total = invoice_params[:items_attributes].values.map do |item|
      item['price'].to_f * item['quantity'].to_f
    end.sum
    if @invoice.update(invoice_params)
      redirect_to(action: 'show', id: @invoice.id)
    else
      render 'index'
    end
  end

  def destroy
    @invoice = Invoice.find(params[:id])
    @invoice.destroy
    redirect_to invoices_path
  end

  def view_invoice
    @invoice = Invoice.find_by(uuid: params[:uuid])
  end

  def send_invoice_mail
    @invoice = Invoice.find(params[:invoice_id])

    ClientMailer.invoice_send_mail(@invoice).deliver
    flash[:notice] = 'Invoice has been sent.'
    @invoice.update(status: 1)
    redirect_to invoices_path
  end

  private

  def invoice_params
    params.require(:invoice).permit(:id, :client_id, :user_id, :invoices_total, :expence_date,
                                    items_attributes: %i[id price quantity invoice_item invoice_id _destroy])
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  def create
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/invoice_helper.rb
module InvoiceHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/clients/new.html.erb
<%= form_with model: @client do |form|%>
<div class="form-group row" > 
       <div class="col">
       <%= form.label :name , "Client Name: " %>
        <%= form.text_field :name %>
      </div>
      <div class="col">
        <%= form.label :email , "Email: " %>
        <%= form.text_field :email %>
      </div>
    </div> 
      <div>
      <%= form.submit "Submit", class: "btn btn-primary" %>
      </div>
 
  <% end %>  

app/views/invoices/_form.html.erb
<%= form_with model: @invoice do |form|%>
<div class="form-group row">
  <div class="col">
    <%= form.label :name , "Client: "%>
    <%= form.select :client_id,
    current_user.clients.collect {|client| [client.name, client.id ]} %>
  </div>
</div>
<div class="form-group" id="fieldsetContainer">
  <%= form.fields_for :items do |item| %>
    <fieldset id="0">
      <div class="form-row" >
        <div class="col" >
          <%= item.label :invoice_item, "Invoice Item: " %>
          <%= item.text_field :invoice_item %>
        </div>
        <div class="col" >
          <%= item.label :price, "Price/item: " %>
          <%= item.number_field :price, min: 0.00, step: 0.001 %>
        </div>
        <div class="col" >
          <%= item.label :quantity , "Quantity: " %>
          <%= item.text_field :quantity, min: 0%>
        </div>
      </div>
      <div class="form-row">
        <%= button_tag('DEL', id: "del-"+item.index.to_s, type: "button ", class: "deleteButtons btn btn-large btn-primary")  %>
      </div>
    </fieldset>
 <% end %>
</div>
<div class="form-group">
    <button id="addItem",type: "button", class = "btn btn-large btn-primary"> Add Item</button>
</div>

<div class="form-group row">
 <div class="col">
    <%= form.label :expence_date, "Expense Date:" %>
    <%= form.date_field :expence_date %>
  </div>
</div>
<div>
    <%= form.submit "Submit", class: "btn btn-primary" %>
</div>

<% end %>

<script>
  const createButton = document.getElementById("addItem")

  function onCreateClick(e) {
    e.preventDefault()
 // const row = document.querySelector('#fieldsetContainer fieldset').cloneNode( true )
    // const invoiceItem = row.querySelector('#invoice_items_attributes_0_invoice_item')
    // invoiceItem.value = ''
    // const invoicePrice = row.querySelector('#invoice_items_attributes_0_price')
    // invoicePrice.value = ''
    // const invoiceQuantity = row.querySelector('#invoice_items_attributes_0_quantity')
    // invoiceQuantity.value = ''
    // document.getElementById('fieldsetContainer').appendChild(row)

    const lastId = document.querySelector('#fieldsetContainer').lastElementChild.id.split("_")[3];

    const newId = parseInt(lastId, 10) + 1;

    // const newFieldset = document.getElementById('0').outerHTML.replace(/0/g,newId);

    const newFieldset =` <fieldset id="${newId}">
      <div class="form-row">
        <div class="col">
          <label for="invoice_items_attributes_${newId}_invoice_item">Invoice Item: </label>
          <input type="text" name="invoice[items_attributes][${newId}][invoice_item]" id="invoice_items_attributes_${newId}_invoice_item">
        </div>
        <div class="col">
          <label for="invoice_items_attributes_${newId}_price">Price/item: </label>
          <input type="text" name="invoice[items_attributes][${newId}][price]" id="invoice_items_attributes_${newId}_price">
        </div>
        <div class="col">
          <label for="invoice_items_attributes_${newId}_quantity">Quantity: </label>
          <input type="text" name="invoice[items_attributes][${newId}][quantity]" id="invoice_items_attributes_${newId}_quantity">
        </div>
      </div>
      <div class="form-row">
        <button name="button" type="button" id="del-${newId}" class="deleteButtons btn-large btn-primary">DEL</button>
      </div>
    </fieldset>`

    document.querySelector('#fieldsetContainer').insertAdjacentHTML(
        'beforeend', newFieldset)
    bindDeleteButtonClickEvents()
  }

  function buttonsArray() {
    allButtons=Array.from(document.querySelectorAll('.deleteButtons'))
    return allButtons
  }

  function onDeleteClick(e) {
    e.preventDefault()

    if(e.target.id !== "del-0") {
    e.target.closest('fieldset').remove()
    }
    else {
     alert ("last item, are you sure?")
    }
  }
  createButton.addEventListener("click", onCreateClick)

  function bindDeleteButtonClickEvents() {
    const array = buttonsArray()
    array.forEach(deleteButton => {
        deleteButton.addEventListener("click", onDeleteClick)

        })
  }

  // const createButton = document.getElementById("addItem")
  // createButton.addEventListener("click", (e)=>{
  //  e.preventDefault()
  //   const lastId = document.querySelector('#fieldsetContainer').lastElementChild.id;

  //   const newId = parseInt(lastId, 10) + 1;

  //   const newFieldset = document.getElementById('0').outerHTML.replace(/0/g,newId);

  //   document.querySelector('#fieldsetContainer').insertAdjacentHTML(
  //       'beforeend', newFieldset
  //   )
  //   const deleteButtons = Array.from(document.querySelectorAll('.deleteButtons'))
  //   deleteButtons.forEach(deleteButton => deleteButton.addEventListener("click", (e)=>{
  //     deleteButtons.forEach(deleteButton => {
  //       if (deleteButton.id == e.target.id) {
  //         deleteButton.closest('fieldset').remove()
  //       }
  //     })
  //   })
  //   )
  // })
  </script>

app/views/invoices/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/invoices/">Home</a>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "New Invoices", new_invoice_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "New Client", new_client_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a
          class="nav-link dropdown-toggle"
          href="#"
          id="navbarDropdown"
          role="button"
          data-toggle="dropdown"
          aria-expanded="false"
        >
          Invoices
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item float-right">
        <a class="nav-link disabled">Action</a>
      </li>
    </ul>
      <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
  </div>
</nav>

app/views/invoices/_table.html.erb
<table class="table table-hover">
  <thead class="thead-light">
    <tr>
      <th scope="col">Invoice_number</th>
      <th scope="col">Client ID</th>
      <th scope="col">Client Name</th>
      <th scope="col">Invoice Total</th>
      <th scope="col">Status</th>
    </tr>
  </thead>
  <% @invoices.each do |invoice| %>
  <tbody>
    <tr>
      <th scope="row">
        <a href="/invoices/<%=invoice.id%>"> <%= invoice.invoice_number %></a>
      </th>
      <td><%= invoice.client_id %></td>
      <td><%= invoice.client.name %></td>
      <td><%= invoice.invoices_total %></td>
      <td><%= invoice.status %>
      <%#= button_to "Sent", { :action => "view_invoice", :uuid => @invoice.uuid }, :method => :get %>
      </td>
    </tr>
  </tbody>
  <% end %>
</table>

app/views/invoices/edit.html.erb
<h1>Edit Invoice</h1>
  <%= form_with model: @invoice do |form|%>
    <div class="form-group row">
      <div class="col">
        <%= form.label :name , "Client: "%>
        <%= form.select :client_id,
        current_user.clients.collect {|client| [client.name, client.id ]} %>
      </div>
    </div>
    <div class="form-group" id="fieldsetContainer">
      <%= form.fields_for :items do |item|%>

          <fieldset id="<%# index %>">
            <div class="form-row" >
              <div class="col">
                <%= item.label :invoice_item, "Invoice Item: " %>
                <%= item.text_field :invoice_item %>
              </div>
              <div class="col">
                <%= item.label :price, "Price/item: " %>
                <%= item.number_field :price, min: 0.00, step: 0.001 %>
              </div>
              <div class="col">
                <%= item.label :quantity , "Quantity: " %>
                <%= item.text_field :quantity, min: 0 %>
              </div>
            </div>
            <div class="form-row">
              <%= item.check_box :_destroy %>
              <%= item.label :_destroy, "Remove Item" %>
            </div>
          </fieldset>
      <% end %>
    </div>
    <div class="form-group">
      <button id="addItemButton",type: "button", class = "btn btn-large btn-primary"> Add Item</button>
    </div>
    <div class="form-group row">
      <div class="col">
          <%= form.label :expence_date, "Expense Date:" %>
          <%= form.date_field :expence_date %>
      </div>
    </div>
    <div>
        <%= form.submit "Submit", class: "btn btn-primary" %>
    </div>
  <% end %>

<script>
    const createButton = document.getElementById("addItemButton")
    function onCreateClick(e) {
      e.preventDefault()
      const lastId = document.querySelector('#fieldsetContainer').lastElementChild.id.split("_")[3];
      const newId = parseInt(lastId, 10) + 1;
      const newFieldset =` <fieldset id="${newId}">
        <div class="form-row">
          <div class="col">
            <label for="invoice_items_attributes_${newId}_invoice_item">Invoice Item: </label>
            <input type="text" name="invoice[items_attributes][${newId}][invoice_item]" id="invoice_items_attributes_${newId}_invoice_item">
          </div>
          <div class="col">
            <label for="invoice_items_attributes_${newId}_price">Price/item: </label>
            <input type="text" name="invoice[items_attributes][${newId}][price]" id="invoice_items_attributes_${newId}_price">
          </div>
          <div class="col">
            <label for="invoice_items_attributes_${newId}_quantity">Quantity: </label>
            <input type="text" name="invoice[items_attributes][${newId}][quantity]" id="invoice_items_attributes_${newId}_quantity">
          </div>
        </div>
        <div class="form-row">
          <button name="button" type="button" id="del-${newId}" class="deleteButtons btn-large btn-primary">DEL</button>
        </div>
      </fieldset>`

      document.querySelector('#fieldsetContainer').insertAdjacentHTML(
        'beforeend', newFieldset)
        bindDeleteButtonClickEvents()
    }
    function buttonsArray() {
    allButtons=Array.from(document.querySelectorAll('.deleteButtons'))
    return allButtons
  }

  function onDeleteClick(e) {
    e.preventDefault()

    if(e.target.id !== "del-0") {
    e.target.closest('fieldset').remove()
    }
    else {
     alert ("last item, are you sure?")
    }
  }
    createButton.addEventListener("click", onCreateClick)
    function bindDeleteButtonClickEvents() {
    const array = buttonsArray()
    array.forEach(deleteButton => {
        deleteButton.addEventListener("click", onDeleteClick)

        })
  }
 </script>

app/views/invoices/index.html.erb
<h1>Hello</h1>
<%= render 'invoices/table'%>


    
			
		

app/views/invoices/new.html.erb
<h1>New Invoice</h1>
<%= render 'invoices/form'%>

app/views/invoices/show.html.erb
<h1>Invoice</h1>

<table class="table table-hover">
  <thead class="thead-light">
    <tr>
      <th scope="col">Invoice_number</th>
      <th scope="col">Client ID</th>
      <th scope="col">Client Name</th>
      <th scope="col">Invoice Total</th>
      <th scope="col">Status</th>
    </tr>
  </thead>
  
  <tbody>
    <tr>
      <th scope="row"><a href= "/invoices/<%=@invoice.id%>/edit"> <%= @invoice.invoice_number %></a></th>
      <td><%= @invoice.client_id %></td>
      <td><%= @invoice.client.name %></td> 
      <td><%= @invoice.invoices_total %></td>
      <td><%= @invoice.status %></td>
    </tr>
  </tbody>
   
</table>
<div class = "buttons">
<%= button_to "Edit", edit_invoice_path, class: "btn btn-large btn-primary", method: :get  %>

<%= button_to "Email To Client", invoice_send_invoice_mail_path(@invoice.id), method: :post, class: "btn btn-large btn-primary" %>

<%= button_to "ViewInvoice", view_invoice_path(:uuid => @invoice.uuid), method: :get, class: "btn btn-large btn-primary" %>


<%= button_to "Delete", { :action => "destroy" }, { class: "btn btn-large btn-primary", :method => :delete}%>
</div>

app/views/invoices/view_invoice.html.erb
<h1>Invoice</h1>

<table class="table table-hover">
  <thead class="thead-light">
    <tr>
      <th scope="col">Invoice_number</th>
      <th scope="col">Client Name</th>
      <th scope="col">Invoice Total</th>
      <th scope="col">Status</th>
    </tr>
  </thead>
  
  <tbody>
    <tr>
      <th scope="row"><%= @invoice.invoice_number %></th>
      <td><%= @invoice.client.name %></td>  
      <td><%= @invoice.invoices_total %></td>
      <td><%= @invoice.status %></td>
    </tr>
  </tbody>
  
</table>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

    <title>MyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'invoices/header'%>
    

    <%= yield %>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    -->
  </body>
</html>